openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'
servers:
- url: http://localhost:8080
  description: localhost
- url: https://api-v3.lenz.ir
  description: Production rest-api
- url: https://preproduction.lenz.ir
  description: Staging rest-api
paths:
  /api/v3/epg/epgsbyday:
    get:
      tags: [User]
      summary: Get EPGs by day
      description: Get EPGs by day
      operationId: getEpgsByDay
      parameters:
      - name: plusDay
        in: query
        description: "Plus day (0: today, 1: tomorrow, 2: after tomorrow, ...) default today"
        required: false
        schema:
          type: integer
          format: date
        example: 0
      - name: loc
        in: query
        description: "Location (Asia/Tehran, ...) default Asia/Tehran"
        required: false
        schema:
          type: string
        example: Asia/Tehran
      responses:
        '200':
          description: OK
          content:
            responseSchema:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EPG'
  /api/v1/admin/epg/epgs:
    post:
      tags: [Admin]
      summary: Create EPG
      description: Create EPG
      operationId: createEpg
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EPG'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EPG'
    get:
      tags: [Admin]
      summary: Get List EPGs
      description: Get List EPGs
      operationId: getListEpgs
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EPG'
  /api/v1/admin/epg/epgs/{epgID}:
    get:
      tags: [Admin]
      summary: Get EPG by ID
      description: Get EPG by ID
      operationId: getEpgByID
      parameters:
      - name: epgID
        in: path
        description: "EPG ID"
        required: true
        schema:
          type: integer
        example: 1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EPG'
    delete:
      tags: [Admin]
      summary: Delete EPG by ID
      description: Delete EPG by ID
      operationId: deleteEpgByID
      parameters:
      - name: epgID
        in: path
        description: "EPG ID"
        required: true
        schema:
          type: integer
        example: 1
      responses:
        '200':
          description: OK
    patch:
      tags: [Admin]
      summary: Update EPG by ID
      description: Update EPG by ID
      operationId: updateEpgByID
      parameters:
      - name: epgID
        in: path
        description: "EPG ID"
        required: true
        schema:
          type: integer
        example: 1
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EPG'



components:
  schemas:
    EPG:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
          example: 1
        title:
          type: string
          example: "Fotbal-Game"
        content_id:
          type: string
          example: "121313"
        content_type:
          type: string
          default: "2"
          example: "2"
          readOnly: true
        start_at:
          type: string
          example: "2023-09-27T08:27:59.492452381Z"
        end_at:
          type: string
          example: "2023-09-27T08:30:59.492452381Z"
        duration:
          type: string
          readOnly: true
        image_url:
          type: string
          example: http://content.lenz.ir/contents-static/images/Ashura-6/8c5bc36caa499597.jpg
      additionalProperties: false
      required:
      - title
      - content_id
      - start_at
      - end_at
      - image_url
